### ISSUE TITLE
Implement livechat

### ISSUE THREAD

**Issue by antoineverin** [TheSecretOrganization/ft_transcendence#13]
with django and websocket?

- [x] setup websocket #22 
- [ ] design messages (think of the differents types)
- [ ] build integration server side
- [ ] build integration client side
