### ISSUE TITLE
Implement Chat

### ISSUE THREAD

**Issue by Neffi42** [TheSecretOrganization/ft_transcendence#157]
- [ ] Create general chat
- [ ] Create private chat
- [ ] Create server chat
- [ ] #111
