### ISSUE TITLE
Implement Game

### ISSUE THREAD

**Issue by Neffi42** [TheSecretOrganization/ft_transcendence#79]
- [x] #105
- [ ] #106
- [x] #107
- [x] #108
- [x] #109
- [ ] #111
- [x] #110 
- [x] #133
- [x] #134
- [ ] #136
- [x] #135
- [x] #137
- [ ] #138
- [x] #162 
- [x] #161

**Comment by Neffi42** [comment]
- [ ] Local game 2 players
- [ ] Local game Ai
- [ ] Online game Create Room
- [ ] Online game join a Room
- [ ] Pong game
- [ ] Invite player
- [ ] Deal with disconnection / exit of one player
